/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Transaksi;
import Model.Detail_Pemesanan;
import Model.Kurir;
import Model.Pegawai;
import Model.Pelanggan;
import Model.Pemesanan;
import Model.Produk;
import com.sun.istack.internal.logging.Logger;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author somala
 */
public class TransaksiView extends javax.swing.JFrame {

    private Transaksi transaksi;
    private ArrayList<Detail_Pemesanan> arrKeranjang;
    private Double hargatotal;

    /**
     * Creates new form TransaksiView
     */
    public TransaksiView() throws SQLException {
        initComponents();
        this.hargatotal = 0.0;
        this.transaksi = new Transaksi();
        this.arrKeranjang = new ArrayList<>();
        this.showComboBoxPelanggan();
        this.showComboBoxPegawai();
        this.showComboBoxKurir();
        this.showComboBoxProduk();
        this.showTableKeranjang();
        this.showTablePemesanan();
    }
    
    public void showComboBoxPelanggan() throws SQLException {
        DefaultComboBoxModel dcbmPelanggan = new DefaultComboBoxModel();

        for (Pelanggan p : this.transaksi.getDataPelanggan()) {
            dcbmPelanggan.addElement(p.getNama_Depan() + " " + p.getNama_Belakang());
        }

        this.cbPelanggan.setModel(dcbmPelanggan);
    }

    public void showComboBoxPegawai() throws SQLException {
        DefaultComboBoxModel dcbmPegawai = new DefaultComboBoxModel();

        for (Pegawai p : this.transaksi.getDataPegawai()) {
            dcbmPegawai.addElement(p.getNama_Depan() + " " + p.getNama_Belakang());
        }

        this.cbPegawai.setModel(dcbmPegawai);
    }

    public void showComboBoxKurir() throws SQLException {
        DefaultComboBoxModel dcbmKurir = new DefaultComboBoxModel();

        for (Kurir k : this.transaksi.getDataKurir()) {
            dcbmKurir.addElement(k.getNama_Perusahaan());
        }

        this.cbKurir.setModel(dcbmKurir);
    }

    public void showComboBoxProduk() throws SQLException {
        DefaultComboBoxModel dcbmProduk = new DefaultComboBoxModel();

        for (Produk p : this.transaksi.getDataProduk()) {
            dcbmProduk.addElement(p.getNama_Produk() + "(STOK " + p.getStok_Produk() + ")");
        }

        this.cbProduk.removeAllItems();
        this.cbProduk.setModel(dcbmProduk);
    }
    
public void showTablePemesanan() throws SQLException {
        DefaultTableModel dtmPesanan = new DefaultTableModel(new String[]
        {"Pelanggan", "Pegawai", "Tanggal Pemesanan", "Harga Total"}, 0 );
        dtmPesanan.setRowCount(0);
        
        for (Pemesanan dp : this.transaksi.getDataPemesanan()){
            dtmPesanan.addRow(new String[]{dp.getPelanggan().getNama_Depan(), 
            dp.getPegawai().getNama_Depan(), dp.getTanggal_Pemesanan().toString(), dp.getHarga_Total().toString()});
        }
        
        this.tblPesanan.setModel(dtmPesanan);
    }

    public void showTableKeranjang() {
        DefaultTableModel dtmKeranjang = new DefaultTableModel(new String[]{"Nama Produk", "Harga Satuan", "Jumlah", "Diskon"}, 0);
        dtmKeranjang.setRowCount(0);

        for (Detail_Pemesanan dp : this.arrKeranjang) {
            dtmKeranjang.addRow(new String[]{dp.getProduk().getNama_Produk(), dp.getProduk().getHarga_Satuan().
                    toString(), dp.getJumlah().toString(), dp.getDiskon().toString()});
        }

        this.tblKeranjang.setModel(dtmKeranjang);
    }

    public void showHargaTotal() {
        this.tfTotalHarga.setText(String.valueOf(this.hargatotal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPelanggan = new javax.swing.JLabel();
        lbPegawai = new javax.swing.JLabel();
        lbKurir = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        lbTglPengiriman = new javax.swing.JLabel();
        lbProduk = new javax.swing.JLabel();
        lbJumlah = new javax.swing.JLabel();
        lbDiskon = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        cbPelanggan = new javax.swing.JComboBox<>();
        cbPegawai = new javax.swing.JComboBox<>();
        cbKurir = new javax.swing.JComboBox<>();
        tfAlamat = new javax.swing.JTextField();
        tfTglPengiriman = new javax.swing.JTextField();
        cbProduk = new javax.swing.JComboBox<>();
        tfJumlah = new javax.swing.JTextField();
        tfDiskon = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        tfTotalHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesanan = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDetailPesanan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPelanggan.setText("Pelanggan        :");

        lbPegawai.setText("Pegawai           :");

        lbKurir.setText("Kurir                 :");

        lbAlamat.setText("Alamat             :");

        lbTglPengiriman.setText("Tgl Pengiriman :");

        lbProduk.setText("Produk             :");

        lbJumlah.setText("Jumlah             :");

        lbDiskon.setText("Diskon              :");

        lbTotal.setText("Total Harga     :");

        cbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPelangganActionPerformed(evt);
            }
        });

        cbPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbKurir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfTglPengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTglPengirimanActionPerformed(evt);
            }
        });

        cbProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tfTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalHargaActionPerformed(evt);
            }
        });

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjang);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPesanan);

        btnDetail.setText("Lihat Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        taDetailPesanan.setColumns(20);
        taDetailPesanan.setRows(5);
        jScrollPane3.setViewportView(taDetailPesanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPelanggan)
                            .addComponent(lbPegawai)
                            .addComponent(lbKurir)
                            .addComponent(lbAlamat)
                            .addComponent(lbTglPengiriman)
                            .addComponent(lbProduk)
                            .addComponent(lbJumlah)
                            .addComponent(lbDiskon))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbPelanggan, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                            .addComponent(cbPegawai, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbKurir, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProduk, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDiskon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTglPengiriman)
                            .addComponent(btnTambah)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetail)
                        .addGap(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPelanggan)
                            .addComponent(cbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPegawai)
                            .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKurir)
                            .addComponent(cbKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAlamat)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTglPengiriman)
                            .addComponent(tfTglPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbProduk)
                            .addComponent(cbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbJumlah)
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDiskon)
                            .addComponent(tfDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotal)
                            .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(btnSimpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(btnDetail)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTglPengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTglPengirimanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTglPengirimanActionPerformed

    private void tfTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalHargaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Pemesanan pemesanan = new Pemesanan();
        try {
            pemesanan.setPelanggan(this.transaksi.getDataPelanggan().get(this.cbPelanggan.getSelectedIndex()));
            pemesanan.setPegawai(this.transaksi.getDataPegawai().get(this.cbPegawai.getSelectedIndex()));
            pemesanan.setKurir(this.transaksi.getDataKurir().get(this.cbKurir.getSelectedIndex()));
            pemesanan.setTanggal_Pemesanan(new Date());
            pemesanan.setTanggal_Pengiriman(new SimpleDateFormat("dd/MM/yyyy").parse(this.tfTglPengiriman.getText()));
            pemesanan.setAlamat_Pengiriman(this.tfAlamat.getText());
            pemesanan.setHarga_Total(this.hargatotal);
            pemesanan.setArrDetail_Pemesanan(this.arrKeranjang);

            this.transaksi.insertTransaksi(pemesanan);
            this.showTablePemesanan();
            this.arrKeranjang = new ArrayList<>();
            this.hargatotal = 0.0;
            this.showComboBoxProduk();
        } catch (SQLException | ParseException err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            Detail_Pemesanan dp = new Detail_Pemesanan();
            dp.setJumlah(Integer.parseInt(this.tfJumlah.getText()));
            dp.setProduk(this.transaksi.getDataProduk().get(this.cbProduk.getSelectedIndex()));

            if (this.tfDiskon.getText().equals("")) {
                //dp.setDiskon(Double.parseDouble(this.tfDiskon.getText()));
                dp.setDiskon(Double.parseDouble("0"));
                hargatotal += this.transaksi.getDataProduk().get(this.cbProduk.getSelectedIndex()).
                        getHarga_Satuan() * Integer.parseInt(this.tfJumlah.getText());
            } else {
                Double diskon = Double.parseDouble(this.tfDiskon.getText());
                Integer hargaTotalProduk = this.transaksi.getDataProduk().get(this.cbProduk.getSelectedIndex()).
                        getHarga_Satuan() * Integer.parseInt(this.tfJumlah.getText());
                Double hargaTotalDiskon = hargaTotalProduk * diskon;
                dp.setDiskon(diskon);
                hargatotal += hargaTotalProduk - hargaTotalDiskon;
            }

            this.showHargaTotal();
            this.arrKeranjang.add(dp);
            this.showTableKeranjang();
            this.tfJumlah.setText("");
            this.tfDiskon.setText("");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        try {
            Pemesanan pemesanan = this.transaksi.getDataPemesanan().get(this.tblPesanan.getSelectedRow());
            String teks = "" + "==================== PELANGGAN ====================" + "\n" + 
                    "Nama Depan : " + pemesanan.getPelanggan().getNama_Depan() + "\n" + 
                    "Nama Belakang : " + pemesanan.getPelanggan().getNama_Belakang() + "\n" + 
                    "Tanggal Lahir : " + new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getPelanggan().getTanggal_Lahir()) 
                    + "\n" + "Alamat : " + pemesanan.getPelanggan().getAlamat() + "\n" + 
                    "Kode Pos : " + pemesanan.getPelanggan().getKode_Pos() + "\n" + 
                    "No. Telp : " + pemesanan.getPelanggan().getNo_Telp() + "\n"
                   
                    + "===================== PEGAWAI =====================" + "\n" + 
                    "Nama Depan : " + pemesanan.getPegawai().getNama_Depan() + "\n" + 
                    "Nama Belakang : " + pemesanan.getPegawai().getNama_Belakang() + "\n" + 
                    "Tanggal Lahir : " + new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getPegawai().getTanggal_Lahir()) + 
                    "\n" + "Alamat : " + pemesanan.getPegawai().getAlamat() + "\n" + 
                    "Kode Pos : " + pemesanan.getPegawai().getKode_Pos() + "\n" + 
                    "No. Telp : " + pemesanan.getPegawai().getNo_Telp() + "\n"
                    
                    + "====================== KURIR ======================" + "\n" + 
                    "Nama Perusahaan : " + pemesanan.getKurir().getNama_Perusahaan() + "\n" + 
                    "No. Telp : " + pemesanan.getKurir().getNo_Tlp() + "\n"
                    
                    + "==================== PEMESANAN ====================" + "\n" + 
                    "Tanggal Pemesanan : " + new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getTanggal_Pemesanan()) + "\n" + 
                    "Tanggal Pengiriman : " + new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getTanggal_Pengiriman()) + "\n" + 
                    "Alamat Pengiriman : " + pemesanan.getAlamat_Pengiriman() + "\n" + 
                    "Harga Total : " + pemesanan.getHarga_Total() + "\n"
                    + "Produk : " + "\n";
            ArrayList<Detail_Pemesanan> dp = pemesanan.getArrDetail_Pemesanan();
            for (int i = 0; i < dp.size(); i++) {
                teks += "\n\n" + (i + 1) + "." + "Perusahaan Pemasok : " + dp.get(i).getProduk().getPemasok().getNama_Perusahaan() 
                        + "\n" + "Alamat Pemasok : " + dp.get(i).getProduk().getPemasok().getAlamat() + "\n" + 
                        "Kode Pos Pemasok : " + dp.get(i).getProduk().getPemasok().getKode_Pos() + "\n" + 
                        "No. Telp Pemasok : " + dp.get(i).getProduk().getPemasok().getNo_Tlp() + "\n" +
                        "Kategori Produk : " + dp.get(i).getProduk().getKategori().getNama_Kategori() + "\n" + 
                        "Nama Produk : " + dp.get(i).getProduk().getNama_Produk() + "\n" + 
                        "Harga Produk : " + dp.get(i).getProduk().getHarga_Satuan() + "\n" + 
                        "Stok Produk : " + dp.get(i).getProduk().getStok_Produk() + "\n" + 
                        "Jumlah Beli Produk : " + dp.get(i).getJumlah() + "\n" + 
                        "Diskon Produk : " + dp.get(i).getDiskon();
            }

            this.taDetailPesanan.setText(teks);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void cbPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TransaksiView().setVisible(true);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbKurir;
    private javax.swing.JComboBox<String> cbPegawai;
    private javax.swing.JComboBox<String> cbPelanggan;
    private javax.swing.JComboBox<String> cbProduk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbDiskon;
    private javax.swing.JLabel lbJumlah;
    private javax.swing.JLabel lbKurir;
    private javax.swing.JLabel lbPegawai;
    private javax.swing.JLabel lbPelanggan;
    private javax.swing.JLabel lbProduk;
    private javax.swing.JLabel lbTglPengiriman;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextArea taDetailPesanan;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTable tblPesanan;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfDiskon;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfTglPengiriman;
    private javax.swing.JTextField tfTotalHarga;
    // End of variables declaration//GEN-END:variables

}
